// flow-typed signature: 6f57fe44dd3661e93d07bae7aa90b91e
// flow-typed version: <<STUB>>/doiuse_v^2.4.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doiuse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'doiuse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'doiuse/cli' {
  declare module.exports: any;
}

declare module 'doiuse/data/features' {
  declare module.exports: any;
}

declare module 'doiuse/lib/browsers' {
  declare module.exports: any;
}

declare module 'doiuse/lib/detect-feature-use' {
  declare module.exports: any;
}

declare module 'doiuse/lib/doiuse' {
  declare module.exports: any;
}

declare module 'doiuse/lib/missing-support' {
  declare module.exports: any;
}

declare module 'doiuse/lib/util' {
  declare module.exports: any;
}

declare module 'doiuse/stream' {
  declare module.exports: any;
}

declare module 'doiuse/test/cli' {
  declare module.exports: any;
}

declare module 'doiuse/test/detect-feature-use' {
  declare module.exports: any;
}

declare module 'doiuse/test/has-keys' {
  declare module.exports: any;
}

declare module 'doiuse/test/missing-support' {
  declare module.exports: any;
}

declare module 'doiuse/test/postcss-plugin' {
  declare module.exports: any;
}

declare module 'doiuse/test/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'doiuse/cli.js' {
  declare module.exports: $Exports<'doiuse/cli'>;
}
declare module 'doiuse/data/features.js' {
  declare module.exports: $Exports<'doiuse/data/features'>;
}
declare module 'doiuse/lib/browsers.js' {
  declare module.exports: $Exports<'doiuse/lib/browsers'>;
}
declare module 'doiuse/lib/detect-feature-use.js' {
  declare module.exports: $Exports<'doiuse/lib/detect-feature-use'>;
}
declare module 'doiuse/lib/doiuse.js' {
  declare module.exports: $Exports<'doiuse/lib/doiuse'>;
}
declare module 'doiuse/lib/missing-support.js' {
  declare module.exports: $Exports<'doiuse/lib/missing-support'>;
}
declare module 'doiuse/lib/util.js' {
  declare module.exports: $Exports<'doiuse/lib/util'>;
}
declare module 'doiuse/stream.js' {
  declare module.exports: $Exports<'doiuse/stream'>;
}
declare module 'doiuse/test/cli.js' {
  declare module.exports: $Exports<'doiuse/test/cli'>;
}
declare module 'doiuse/test/detect-feature-use.js' {
  declare module.exports: $Exports<'doiuse/test/detect-feature-use'>;
}
declare module 'doiuse/test/has-keys.js' {
  declare module.exports: $Exports<'doiuse/test/has-keys'>;
}
declare module 'doiuse/test/missing-support.js' {
  declare module.exports: $Exports<'doiuse/test/missing-support'>;
}
declare module 'doiuse/test/postcss-plugin.js' {
  declare module.exports: $Exports<'doiuse/test/postcss-plugin'>;
}
declare module 'doiuse/test/stream.js' {
  declare module.exports: $Exports<'doiuse/test/stream'>;
}
