// flow-typed signature: 74f658ba597bae7ce969f4fd2828439f
// flow-typed version: <<STUB>>/eslint-config-gw_v^1.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-gw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-gw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-gw/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/jsdoc' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/test/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/test/test' {
  declare module.exports: any;
}

declare module 'eslint-config-gw/test/validate-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-gw/index' {
  declare module.exports: $Exports<'eslint-config-gw'>;
}
declare module 'eslint-config-gw/index.js' {
  declare module.exports: $Exports<'eslint-config-gw'>;
}
declare module 'eslint-config-gw/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/best-practices'>;
}
declare module 'eslint-config-gw/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/es6'>;
}
declare module 'eslint-config-gw/rules/flow.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/flow'>;
}
declare module 'eslint-config-gw/rules/jsdoc.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/jsdoc'>;
}
declare module 'eslint-config-gw/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/node'>;
}
declare module 'eslint-config-gw/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/react'>;
}
declare module 'eslint-config-gw/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/strict'>;
}
declare module 'eslint-config-gw/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/style'>;
}
declare module 'eslint-config-gw/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-gw/rules/variables'>;
}
declare module 'eslint-config-gw/test/basic.js' {
  declare module.exports: $Exports<'eslint-config-gw/test/basic'>;
}
declare module 'eslint-config-gw/test/test.js' {
  declare module.exports: $Exports<'eslint-config-gw/test/test'>;
}
declare module 'eslint-config-gw/test/validate-config.js' {
  declare module.exports: $Exports<'eslint-config-gw/test/validate-config'>;
}
