// flow-typed signature: 93dc10d8f7ae883ea228d77482717468
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_vhttps://github.com/MicheleBertoli/extract-text-webpack-plugin/tarball/order-undefined-error/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-text-webpack-plugin/example/dep' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/example/dep2' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/example/entry' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/example/entry2' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/example/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/ExtractedModule' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/loader' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/OrderUndefinedError' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-chunk/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-chunk/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/a' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/b' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries/a' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries/b' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/multiple-entries/a' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/multiple-entries/b' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/multiple-entries/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/nested/file' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/nested/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/nested/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/order-undefined-error/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/order-undefined-error/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/simple/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/simple/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/splitted-chunk/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/splitted-chunk/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/a' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/b' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/webpack.config' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/test/TestCases.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-text-webpack-plugin/example/dep.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/example/dep'>;
}
declare module 'extract-text-webpack-plugin/example/dep2.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/example/dep2'>;
}
declare module 'extract-text-webpack-plugin/example/entry.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/example/entry'>;
}
declare module 'extract-text-webpack-plugin/example/entry2.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/example/entry2'>;
}
declare module 'extract-text-webpack-plugin/example/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/example/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/ExtractedModule.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/ExtractedModule'>;
}
declare module 'extract-text-webpack-plugin/index' {
  declare module.exports: $Exports<'extract-text-webpack-plugin'>;
}
declare module 'extract-text-webpack-plugin/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin'>;
}
declare module 'extract-text-webpack-plugin/loader.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/loader'>;
}
declare module 'extract-text-webpack-plugin/OrderUndefinedError.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/OrderUndefinedError'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-chunk/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-chunk/index'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-chunk/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-chunk/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/a.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/a'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/b.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/b'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-multiple-entries-shared/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries/a.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-multiple-entries/a'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries/b.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-multiple-entries/b'>;
}
declare module 'extract-text-webpack-plugin/test/cases/merging-multiple-entries/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/merging-multiple-entries/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/multiple-entries/a.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/multiple-entries/a'>;
}
declare module 'extract-text-webpack-plugin/test/cases/multiple-entries/b.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/multiple-entries/b'>;
}
declare module 'extract-text-webpack-plugin/test/cases/multiple-entries/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/multiple-entries/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/nested/file.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/nested/file'>;
}
declare module 'extract-text-webpack-plugin/test/cases/nested/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/nested/index'>;
}
declare module 'extract-text-webpack-plugin/test/cases/nested/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/nested/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/order-undefined-error/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/order-undefined-error/index'>;
}
declare module 'extract-text-webpack-plugin/test/cases/order-undefined-error/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/order-undefined-error/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/simple/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/simple/index'>;
}
declare module 'extract-text-webpack-plugin/test/cases/simple/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/simple/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/splitted-chunk/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/splitted-chunk/index'>;
}
declare module 'extract-text-webpack-plugin/test/cases/splitted-chunk/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/splitted-chunk/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/a.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/a'>;
}
declare module 'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/b.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/b'>;
}
declare module 'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/webpack.config.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/cases/splitted-multiple-entries/webpack.config'>;
}
declare module 'extract-text-webpack-plugin/test/TestCases.test.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/test/TestCases.test'>;
}
