// flow-typed signature: 685fe4380e48000ffc3f3acc9c061585
// flow-typed version: <<STUB>>/stylelint-config-gw_v^1.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-gw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-gw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-gw/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-gw/index' {
  declare module.exports: $Exports<'stylelint-config-gw'>;
}
declare module 'stylelint-config-gw/index.js' {
  declare module.exports: $Exports<'stylelint-config-gw'>;
}
declare module 'stylelint-config-gw/test/index.js' {
  declare module.exports: $Exports<'stylelint-config-gw/test/index'>;
}
